[tool.poetry]
name = "carwall-1"
version = "0.1.0"
description = ""
authors = ["AugustoPicardo <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
PyDrive2 = "^1.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
